#!/bin/bash

###############################################################################
# Frontend Config Update Script
#
# This script updates config.js with actual values from AWS Parameter Store
# after CDK deployment. It should be run after `cdk deploy`.
#
# Usage:
#   ./update-frontend-config.sh [environment]
#
# Example:
#   ./update-frontend-config.sh dev
#   ./update-frontend-config.sh prod
#
# Environment variables:
#   AWS_REGION - AWS region (default: us-east-1)
###############################################################################

set -e

# Default values
ENVIRONMENT="${1:-dev}"
AWS_REGION="${AWS_REGION:-us-east-1}"
PROJECT_NAME="co2-analysis"

# Color codes for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Helper functions
log_info() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

log_warn() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Check if AWS CLI is installed
if ! command -v aws &> /dev/null; then
    log_error "AWS CLI is not installed. Please install it first."
    exit 1
fi

log_info "Updating frontend config for environment: ${ENVIRONMENT}"

# Fetch values from Parameter Store
log_info "Fetching API Gateway URL from Parameter Store..."
API_GATEWAY_URL=$(aws ssm get-parameter \
    --name "/${PROJECT_NAME}/${ENVIRONMENT}/compute/api-gateway/url" \
    --region "${AWS_REGION}" \
    --query 'Parameter.Value' \
    --output text 2>/dev/null || echo "")

if [ -z "$API_GATEWAY_URL" ]; then
    log_warn "API Gateway URL not found in Parameter Store. Using default."
    API_GATEWAY_URL="http://localhost:5000"
fi

log_info "Fetching CloudFront URL from Parameter Store..."
CLOUDFRONT_URL=$(aws ssm get-parameter \
    --name "/${PROJECT_NAME}/${ENVIRONMENT}/frontend/cloudfront/url" \
    --region "${AWS_REGION}" \
    --query 'Parameter.Value' \
    --output text 2>/dev/null || echo "")

if [ -z "$CLOUDFRONT_URL" ]; then
    log_warn "CloudFront URL not found in Parameter Store. Leaving empty."
    CLOUDFRONT_URL=""
fi

log_info "Retrieved configuration:"
log_info "  API Gateway URL: ${API_GATEWAY_URL}"
log_info "  CloudFront URL: ${CLOUDFRONT_URL}"

# Update config.js
CONFIG_FILE="../config.js"

if [ ! -f "$CONFIG_FILE" ]; then
    log_error "config.js not found at ${CONFIG_FILE}"
    exit 1
fi

log_info "Updating ${CONFIG_FILE}..."

# Create updated config.js content
cat > "$CONFIG_FILE" << EOF
/**
 * Frontend Configuration
 *
 * This file contains configuration values that are environment-specific.
 * Auto-generated by update-frontend-config.sh on $(date)
 */

const CONFIG = {
  // API Gateway URL - populated from Parameter Store during deployment
  // Format: https://{api-id}.execute-api.{region}.amazonaws.com/{stage}
  API_GATEWAY_URL: '${API_GATEWAY_URL}',

  // CloudFront URL - populated from Parameter Store during deployment
  CLOUDFRONT_URL: '${CLOUDFRONT_URL}',

  // Environment
  ENVIRONMENT: '${ENVIRONMENT}',

  // Cache settings
  CACHE_ENABLED: true,

  // API endpoints
  ENDPOINTS: {
    REASONING: '/reasoning',
    GEOJSON: '/data/geojson',
  }
};

// Make CONFIG available globally
window.APP_CONFIG = CONFIG;
EOF

log_info "✓ Successfully updated config.js"

# Upload to S3 if bucket exists
log_info "Fetching S3 bucket name from Parameter Store..."
S3_BUCKET=$(aws ssm get-parameter \
    --name "/${PROJECT_NAME}/${ENVIRONMENT}/frontend/s3/website-bucket-name" \
    --region "${AWS_REGION}" \
    --query 'Parameter.Value' \
    --output text 2>/dev/null || echo "")

if [ -n "$S3_BUCKET" ]; then
    log_info "Uploading config.js to S3 bucket: ${S3_BUCKET}"
    aws s3 cp "$CONFIG_FILE" "s3://${S3_BUCKET}/config.js" \
        --region "${AWS_REGION}" \
        --content-type "application/javascript"

    log_info "✓ Successfully uploaded config.js to S3"

    # Invalidate CloudFront cache
    DISTRIBUTION_ID=$(aws ssm get-parameter \
        --name "/${PROJECT_NAME}/${ENVIRONMENT}/frontend/cloudfront/distribution-id" \
        --region "${AWS_REGION}" \
        --query 'Parameter.Value' \
        --output text 2>/dev/null || echo "")

    if [ -n "$DISTRIBUTION_ID" ]; then
        log_info "Invalidating CloudFront cache for distribution: ${DISTRIBUTION_ID}"
        aws cloudfront create-invalidation \
            --distribution-id "${DISTRIBUTION_ID}" \
            --paths "/config.js" \
            --region "${AWS_REGION}" > /dev/null
        log_info "✓ CloudFront cache invalidated"
    fi
else
    log_warn "S3 bucket not found. Skipping upload."
fi

log_info "✓ Frontend configuration update complete!"
log_info ""
log_info "Next steps:"
log_info "  1. Verify the updated config.js file"
log_info "  2. Test your application at: ${CLOUDFRONT_URL}"
log_info "  3. Check API integration with: ${API_GATEWAY_URL}"
